inherit_from: "configs/mono/scannet/base_config.yaml"
Dataset:
  dataset_path: "datasets/scannet/scans/scene0169_00"
  Calibration:
    fx: 577.590698
    fy: 578.729797
    cx: 318.905426
    cy: 242.683609
    k1: 0.
    k2: 0.
    p1: 0.
    p2: 0.0
    k3: 0.
    width: 640
    height: 480
    depth_scale: 1000.0
    distorted: False

# # scene0000_00
# scene0059_00
# scene0062_00
# scene0103_00
# scene0106_00
# scene0126_00
# scene0169_00
# scene0181_00
# scene0207_00